[features]
seeds = false
[programs.localnet]
mycalculatordapp = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "/Users/macmini/.config/solana/id.json"

[scripts]
test = "node tests/mycalculatordapp.test.js"
